[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comfystream"
version = "0.0.2"
dependencies = [
    "asyncio",
    "comfyui @ git+https://github.com/hiddenswitch/ComfyUI.git@ce3583ad42c024b8f060d0002cbe20c265da6dc8",
    "toml",
    "aiortc",
    "aiohttp",
    "twilio",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Homepage = "https://github.com/yondonfu/comfystream"

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src", "nodes"]}}


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
