models:
  # Base models
  dreamshaper-v8:
    name: "Dreamshaper v8"
    url: "https://civitai.com/api/download/models/128713?type=Model&format=SafeTensor&size=pruned&fp=fp16"
    path: "checkpoints/SD1.5/dreamshaper-8.safetensors"
    type: "checkpoint"

  # DMD models
  dreamshaper-dmd:
    name: "Dreamshaper DMD"
    url: "https://huggingface.co/aaronb/dreamshaper-8-dmd-1kstep/resolve/main/diffusion_pytorch_model.safetensors"
    path: "unet/dreamshaper-8-dmd-1kstep.safetensors"
    type: "unet"
    extra_files:
      - url: "https://huggingface.co/aaronb/dreamshaper-8-dmd-1kstep/raw/main/config.json"
        path: "unet/dreamshaper-8-dmd-1kstep.json"

  # Depth Anything ONNX model
  depthanything-onnx:
    name: "DepthAnything ONNX"
    url: "https://huggingface.co/yuvraj108c/Depth-Anything-2-Onnx/resolve/main/depth_anything_v2_vitb.onnx?download=true"
    path: "tensorrt/depth-anything/depth_anything_vitl14.onnx"

  # TAESD models
  taesd:
    name: "TAESD"
    url: "https://raw.githubusercontent.com/madebyollin/taesd/main/taesd_decoder.pth"
    path: "vae_approx/taesd_decoder.pth"
    type: "vae_approx"
    extra_files:
      - url: "https://raw.githubusercontent.com/madebyollin/taesd/main/taesd_encoder.pth"
        path: "vae_approx/taesd_encoder.pth"

  # ControlNet models
  controlnet-depth:
    name: "ControlNet Depth"
    url: "https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_v11f1p_sd15_depth_fp16.safetensors"
    path: "controlnet/control_v11f1p_sd15_depth_fp16.safetensors"
    type: "controlnet" 

  controlnet-mediapipe-face:
    name: "ControlNet MediaPipe Face"
    url: "https://huggingface.co/CrucibleAI/ControlNetMediaPipeFace/resolve/main/control_v2p_sd15_mediapipe_face.safetensors"
    path: "controlnet/control_v2p_sd15_mediapipe_face.safetensors"
    type: "controlnet"

  # Lora models
  ral-polygon-sd15:
    name: "ral-polygon-sd15"
    url: "https://huggingface.co/Livepeer-Studio/comfystream_loras/resolve/main/ral-polygon-sd15.safetensors"
    path: "loras/SD1.5/ral-polygon-sd15.safetensors"
    type: "lora"

  ral-chrome-sdxl:
    name: "ral-chrome-sd15"
    url: "https://civitai.com/api/download/models/276570?type=Model&format=SafeTensor"
    path: "loras/SD1.5/ral-chrome-sd15.safetensors"
    type: "lora"

  cliptext:
    name: "ClipTextModel"
    url: "https://huggingface.co/Lykon/dreamshaper-8/resolve/main/text_encoder/model.fp16.safetensors"
    path: "text_encoders/CLIPText/model.fp16.safetensors"
    type: "text_encoder"
    extra_files:
      - url: "https://huggingface.co/Lykon/dreamshaper-8/resolve/main/text_encoder/config.json"
        path: "text_encoders/CLIPText/config.json"